# Generated by Django 4.2.6 on 2024-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('Bikes', 'Two wheelers'), ('Cars', 'Four wheeler')], max_length=11)),
            ],
        ),
    ]
