# Generated by Django 4.2.6 on 2024-02-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Port_number',
            field=models.IntegerField(default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
