# Generated by Django 4.2.6 on 2024-02-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_reservation_number_reservation_port_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Port_number',
            field=models.IntegerField(),
        ),
    ]
