# Generated by Django 4.2.6 on 2024-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('Bike', 'Two wheeler'), ('Car', 'Four wheeler')], max_length=11),
        ),
    ]
