# Generated by Django 4.2.6 on 2024-02-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_reservation_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='Port_number',
            new_name='charging_Port_number',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
