# Generated by Django 4.2.6 on 2024-02-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_port_number_reservation_charging_port_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('Level_1', 'Very Slow'), ('Level_2', 'Slow'), ('Level_3', 'Fast')], max_length=11),
        ),
    ]
