# Generated by Django 4.2.6 on 2024-03-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_reservation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='category',
            field=models.CharField(choices=[('Level_1', 'Slow'), ('Level_2', 'Normal'), ('Level_3', 'Fast')], max_length=11),
        ),
    ]
