# Generated by Django 4.2.6 on 2024-03-03 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_reservation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
