# Generated by Django 4.2.6 on 2024-03-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
