# Generated by Django 4.2.6 on 2024-03-20 14:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0008_e_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='E_vehicle',
            new_name='payment',
        ),
    ]
