# Generated by Django 4.2.6 on 2024-03-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_e_vehicle_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='DL_number',
            new_name='Driving_license_number',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='booked_id',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user',
            new_name='name',
        ),
    ]
