# Generated by Django 4.2.6 on 2024-04-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_booked_id_payment_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Driving_license_number',
            field=models.CharField(default=23938, max_length=100),
            preserve_default=False,
        ),
    ]
