# Generated by Django 4.2.6 on 2024-03-21 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_dl_number_payment_driving_license_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='booked_id',
            new_name='book_id',
        ),
    ]
