# Generated by Django 6.0.3 on 2026-04-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_rename_dl_number_payment_driving_license_number_and_more'),
        ('book', '0011_payment_driving_license_number'),
        ('book', '0011_rename_booked_id_payment_book_id'),
    ]

    operations = [
    ]
