from collections import OrderedDict

all_locations = OrderedDict({
    'Chennai': {
        'Bengaluru': {
            'Chennai': {'distance': 0, 'link': 'https://maps.app.goo.gl/Mjt5Loatmq6BR7aL8'},
            'Chembarampakkam': {'distance': 80, 'link': 'https://maps.app.goo.gl/rZktWpL7ZUN8LxHn6'},
            'Kanchipuram': {'distance': 60, 'link': 'https://maps.app.goo.gl/1G8mfJmv1UUTTRDk6'},
            'Vellore': {'distance': 100, 'link': 'https://maps.app.goo.gl/Pho3zwYYVSnUVYzXA'},
            'Chithur': {'distance': 150, 'link': 'https://maps.app.goo.gl/BMZdx2Zbn9BjmYzh8'},
            'Kolar, Karnataka': {'distance': 200, 'link': 'https://maps.app.goo.gl/UYC7hQLhZJDiKL1C9'},
            'Bengaluru': {'distance': 260, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
        },
        'Pondicherry':{
            'Chennai': {'distance':0,'link':'https://maps.app.goo.gl/Mjt5Loatmq6BR7aL8'},
            'Chennai,perungudi': {'distance':16,'link':'https://maps.app.goo.gl/rvhaHYEwS9jHV7fh7'},
            'Sozhinganallur':{'distance':25,'link':'https://maps.app.goo.gl/tfyqKx9unhnAhmyo6'},
            'Mahabalipuram':{'distance':60,'link':'https://maps.app.goo.gl/TNYDsDaLxyusjKth8'},
            'Manjakuppam':{'distance':98,'link':'https://maps.app.goo.gl/atxt7PwB5ocvii756'},
            'Pondicherry':{'distance':150,'link':'https://maps.app.goo.gl/oRuSAxWBtJzxcioa7'},
        },
        'Trichy':{
            'Chennai': {'distance':0,'link':'https://maps.app.goo.gl/57AeGnVCKaDrBJwG7'},
            'Meenampakkam':{'distance':24,'link':'https://maps.app.goo.gl/8AtXufRKis6ur3wh7'},
            'Maraimalainagar':{'distance':48,'link':'https://maps.app.goo.gl/okBZAPmJAjFwhyhY9'},
            'Tindivanam':{'distance':130,'link':'https://maps.app.goo.gl/YrEFt5iuCwzubfXr6'},
            'Ulundurpet':{'distance':205,'link':'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'Perambalur':{'distance':275,'link':'https://maps.app.goo.gl/9XdzGiy4k5dPCKjk6'},
            'Samayapuram near':{'distance':315,'link':'https://maps.app.goo.gl/USbqTd3k6RZAPuPN7'},
            'Trichy':{'distance':330,'link':'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
        },
        'Coimbatore':{
            'Chennai': {'distance':0,'link':'https://maps.app.goo.gl/57AeGnVCKaDrBJwG7'},
            'Meenampakkam':{'distance':24,'link':'https://maps.app.goo.gl/8AtXufRKis6ur3wh7'},
            'Maraimalainagar':{'distance':48,'link':'https://maps.app.goo.gl/okBZAPmJAjFwhyhY9'},
            'Tindivanam':{'distance':130,'link':'https://maps.app.goo.gl/YrEFt5iuCwzubfXr6'},
            'Ulundurpet':{'distance':205,'link':'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'Kallakuruchy':{'distance':245,'link':'https://maps.app.goo.gl/3HoRLnqhX9SEhfgL9'},
            'Attur':{'distance':290,'link':'https://maps.app.goo.gl/m8uaRUauA2CC7mzT7'},
            'Salem':{'distance':345,'link':'https://maps.app.goo.gl/HtcUFhGtGYRYqKt4A'},
            'Perundurai':{'distance':425,'link':'https://maps.app.goo.gl/Tqp2xL2SyZxfZtdm7'},
            'Coimbatore':{'distance':505,'link':'https://maps.app.goo.gl/Ro5nXL5WNWB3mbyZ7'},
        },
        'Arni':{
            'Porur,Chennai':{'distance':0,'link':'https://maps.app.goo.gl/Mjt5Loatmq6BR7aL8'},
            'Tambaram':{'distance':30,'link':'https://maps.app.goo.gl/PFTRnJCTaziGpCRv8'},
            'Maraimalainagar':{'distance':56,'link':'https://maps.app.goo.gl/LDQ8Qy7wSrSQjBCX9'},
            'Kanchipuram':{'distance':85,'link':'https://maps.app.goo.gl/sVyD2ZYwPEKSz6sk6'},
            'Arni':{'distance':142,'link':'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
        },
        
    },
    'Pondicherry': {
        'Coimbatore': {
            'Pondicherry': {'distance': 0, 'link': 'https://maps.app.goo.gl/QXecgXf3kqshrtqx5'},
            'Ulundurpet': {'distance': 50, 'link': 'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'Kallakuruchy': {'distance': 80, 'link': 'https://maps.app.goo.gl/3HoRLnqhX9SEhfgL9'},
            'Attur': {'distance': 120, 'link': 'https://maps.app.goo.gl/m8uaRUauA2CC7mzT7'},
            'Salem': {'distance': 150, 'link': 'https://maps.app.goo.gl/HtcUFhGtGYRYqKt4A'},
            'Perundurai': {'distance': 180, 'link': 'https://maps.app.goo.gl/Tqp2xL2SyZxfZtdm7'},
            'Coimbatore': {'distance': 220, 'link': 'https://maps.app.goo.gl/Ro5nXL5WNWB3mbyZ7'},
        },
        'Thirchy': {
            'Pondicherry': {'distance': 0, 'link': 'https://maps.app.goo.gl/QXecgXf3kqshrtqx5'},
            'Vilupuram': {'distance': 60, 'link': 'https://maps.app.goo.gl/hkubd6ZevBRzPNcZ9'},
            'Ulundurpet': {'distance': 100, 'link': 'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'Perambalur': {'distance': 140, 'link': 'https://maps.app.goo.gl/9XdzGiy4k5dPCKjk6'},
            'Samayapuram near': {'distance': 180, 'link': 'https://maps.app.goo.gl/USbqTd3k6RZAPuPN7'},
            'Trichy': {'distance': 220, 'link': 'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
        },
        'Bengaluru': {
            'Pondicherry': {'distance': 0, 'link': 'https://maps.app.goo.gl/LhxRtjpLoh1Hu6ZFA'},
            'Tindivanam': {'distance': 50, 'link': 'https://maps.app.goo.gl/YrEFt5iuCwzubfXr6'},
            'Tiruvannamalai': {'distance': 80, 'link': 'https://maps.app.goo.gl/XH5oUWD9aDhDCwJo9'},
            'Mathur': {'distance': 120, 'link': 'https://maps.app.goo.gl/m7qXqVA9ZocWpzGo6'},
            'Hosur': {'distance': 150, 'link': 'https://maps.app.goo.gl/qrhccqZZFPHhYYKE8'},
            'Bengaluru': {'distance': 180, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
        },
        'Chennai': {
            'Pondicherry': {'distance': 0, 'link': 'https://maps.app.goo.gl/oRuSAxWBtJzxcioa7'},
            'Manjakuppam': {'distance': 50, 'link': 'https://maps.app.goo.gl/atxt7PwB5ocvii756'},
            'Mahabalipuram': {'distance': 80, 'link': 'https://maps.app.goo.gl/TNYDsDaLxyusjKth8'},
            'Sozhinganallur': {'distance': 120, 'link': 'https://maps.app.goo.gl/tfyqKx9unhnAhmyo6'},
            'Chennai,perungudi': {'distance': 150, 'link': 'https://maps.app.goo.gl/rvhaHYEwS9jHV7fh7'},
            'Chennai': {'distance': 180, 'link': 'https://maps.app.goo.gl/Mjt5Loatmq6BR7aL8'},
        },
        'Arni':{
            'Pondycherry':{'distance':0,'link':'https://maps.app.goo.gl/nVxSdDynVXph5Hrq9'},
            'Tindivanam':{'distance':40,'link':'https://maps.app.goo.gl/PfXPLyB6LyxE9ahs5'},
            'Tiruvannamalai':{'distance':84,'link':'https://maps.app.goo.gl/1Y5L2vqCfyX2CQ659'},
            'Arni':{'distance':120,'link':'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
        },
    },
    'Arni': {
        'Pondicherry': {
            'Arni': {'distance': 0, 'link': 'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
            'Tiruvannamalai': {'distance': 50, 'link': 'https://maps.app.goo.gl/1Y5L2vqCfyX2CQ659'},
            'Tindivanam': {'distance': 80, 'link': 'https://maps.app.goo.gl/PfXPLyB6LyxE9ahs5'},
            'pondicherry': {'distance': 120, 'link': 'https://maps.app.goo.gl/nVxSdDynVXph5Hrq9'},
        },
        'Chennai': {
            'Arni': {'distance': 0, 'link': 'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
            'kanchipuram': {'distance': 50, 'link': 'https://maps.app.goo.gl/sVyD2ZYwPEKSz6sk6'},
            'maraimalainagar': {'distance': 80, 'link': 'https://maps.app.goo.gl/LDQ8Qy7wSrSQjBCX9'},
            'tambaram': {'distance': 120, 'link': 'https://maps.app.goo.gl/PFTRnJCTaziGpCRv8'},
            'Porur': {'distance': 150, 'link': 'https://maps.app.goo.gl/Mjt5Loatmq6BR7aL8'},
        },
        'Bengaluru': {
            'Arni': {'distance': 0, 'link': 'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
            'vellore': {'distance': 50, 'link': 'https://maps.app.goo.gl/p9k9ofUwXjUwkj3p9'},
            'vaniyambadi': {'distance': 80, 'link': 'https://maps.app.goo.gl/cQh61DEXp2uFBCmW9'},
            'Krishnagiri': {'distance': 120, 'link': 'https://maps.app.goo.gl/m7qXqVA9ZocWpzGo6'},
            'hosur': {'distance': 150, 'link': 'https://maps.app.goo.gl/odZMRHaskQk61FPp8'},
            'bengaluru': {'distance': 180, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
        },
        'Trichy': {
            'Arni': {'distance': 0, 'link': ' https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
            'villupuram': {'distance': 50, 'link': 'https://maps.app.goo.gl/fXfXyZnGYNhLiEGNA'},
            'ulunthurpet': {'distance': 80, 'link': 'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'perambalur': {'distance': 120, 'link': 'https://maps.app.goo.gl/Ls912j6Bm1AweBs57'},
            'trichy': {'distance': 150, 'link': 'https://maps.app.goo.gl/BPTugdQjPA7poysh8'},
        },
        'Coimbatore':{
            'Arani':{'distance':0,'link':'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
            'Tiruvannamalai':{'distance':74,'link':'https://maps.app.goo.gl/XH5oUWD9aDhDCwJo9'},
            'Attur':{'distance':160,'link':'https://maps.app.goo.gl/m8uaRUauA2CC7mzT7'},
            'Salem':{'distance':190,'link':'https://maps.app.goo.gl/HtcUFhGtGYRYqKt4A'},
            'Perundurai':{'distance':270,'link':'https://maps.app.goo.gl/Tqp2xL2SyZxfZtdm7'},
            'Coimbatore':{'distance':350,'link':'https://maps.app.goo.gl/Ro5nXL5WNWB3mbyZ7'},
        },
    },
    'Trichy': {
        'Pondicherry': {
            'Trichy': {'distance': 0, 'link': 'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
            'Samayapuram near': {'distance': 50, 'link': 'https://maps.app.goo.gl/USbqTd3k6RZAPuPN7'},
            'Perambalur': {'distance': 80, 'link': 'https://maps.app.goo.gl/9XdzGiy4k5dPCKjk6'},
            'Ulundurpet': {'distance': 120, 'link': 'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'Vilupuram': {'distance': 150, 'link': 'https://maps.app.goo.gl/hkubd6ZevBRzPNcZ9'},
            'Pondicherry': {'distance': 180, 'link': 'https://maps.app.goo.gl/QXecgXf3kqshrtqx5'},
        },
        'Coimbatore': {
            'Trichy': {'distance': 0, 'link': 'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
            'Madurai, bypass': {'distance': 50, 'link': 'https://maps.app.goo.gl/gUZdzPtpXvvM1Wx59'},
            'Thennilai': {'distance': 80, 'link': 'https://maps.app.goo.gl/AMmbbZgVoiDvi1u19'},
            'Coimbatore': {'distance': 120, 'link': 'https://maps.app.goo.gl/UgpBBViaVeWKMr8W6'},
        },
        'Chennai': {
            'Trichy': {'distance': 0, 'link': 'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
            'Samayapuram near': {'distance': 50, 'link': 'https://maps.app.goo.gl/USbqTd3k6RZAPuPN7'},
            'Perambalur': {'distance': 80, 'link': 'https://maps.app.goo.gl/9XdzGiy4k5dPCKjk6'},
            'Ulundurpet': {'distance': 120, 'link': 'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'Tindivanam': {'distance': 150, 'link': 'https://maps.app.goo.gl/YrEFt5iuCwzubfXr6'},
            'Maraimalainagar': {'distance': 180, 'link': 'https://maps.app.goo.gl/okBZAPmJAjFwhyhY9'},
            'Meenampakkam': {'distance': 200, 'link': 'https://maps.app.goo.gl/8AtXufRKis6ur3wh7'},
            'Chennai': {'distance': 230, 'link': 'https://maps.app.goo.gl/57AeGnVCKaDrBJwG7'},
        },
        'Bengaluru': {
            'Trichy': {'distance': 0, 'link': 'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
            'Paramathi': {'distance': 50, 'link': 'https://maps.app.goo.gl/dAsGtbaMo9RVC4F69'},
            'Salem': {'distance': 80, 'link': 'https://maps.app.goo.gl/qD99cER1BPM4aLg88'},
            'Darmapuri': {'distance': 120, 'link': 'https://maps.app.goo.gl/uUCi83ja7CwBQ44Z7'},
            'Mathur': {'distance': 150, 'link': 'https://maps.app.goo.gl/m7qXqVA9ZocWpzGo6'},
            'Osur': {'distance': 180, 'link': 'https://maps.app.goo.gl/qrhccqZZFPHhYYKE8'},
            'Bengaluru': {'distance': 200, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
        },
        'Arni':{
            'Trichy':{'distance':0,'link':'https://maps.app.goo.gl/BPTugdQjPA7poysh8'},
            'perambalur':{'distance': 55,'link':'https://maps.app.goo.gl/Ls912j6Bm1AweBs57'},
            'ulunthurpet':{'distance':120,'link':'https://maps.app.goo.gl/us1NReBhemjnSs8Q6'},
            'villupuram':{'distance':165,'link':'https://maps.app.goo.gl/fXfXyZnGYNhLiEGNA'},
            'Arni':{'distance':245,'link':'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
        },
    },
    'Bengaluru': {
        'Chennai': {
            'Bengaluru': {'distance': 0, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
            'Kolar, Karnataka': {'distance': 50, 'link': 'https://maps.app.goo.gl/UYC7hQLhZJDiKL1C9'},
            'Chithur': {'distance': 80, 'link': 'https://maps.app.goo.gl/BMZdx2Zbn9BjmYzh8'},
            'Vellore': {'distance': 120, 'link': 'https://maps.app.goo.gl/Pho3zwYYVSnUVYzXA'},
            'Kanchipuram': {'distance': 150, 'link': 'https://maps.app.goo.gl/1G8mfJmv1UUTTRDk6'},
            'Chembarampakkam': {'distance': 180, 'link': 'https://maps.app.goo.gl/rZktWpL7ZUN8LxHn6'},
            'Chennai': {'distance': 230, 'link': 'https://maps.app.goo.gl/Mjt5Loatmq6BR7aL8'},
        },
        'Coimbatore': {
            'Bengaluru': {'distance': 0, 'link': 'https://maps.app.goo.gl/sVnzCdBMTPVChvcw7'},
            'Vidyaranapura': {'distance': 50, 'link': 'https://maps.app.goo.gl/KCQLGgMuRAbQzz478'},
            'Malavalli, Mysore': {'distance': 80, 'link': 'https://maps.app.goo.gl/utHT1dzxz8BpAXf3A'},
            'Ooty Road': {'distance': 120, 'link': 'https://maps.app.goo.gl/jfRUaVo9EsM6rRFW6'},
            'Pudumund, Ooty': {'distance': 150, 'link': 'https://maps.app.goo.gl/bgvQvM7fwUVWsnmNA'},
            'Mettupalayam': {'distance': 180, 'link': 'https://maps.app.goo.gl/j3Sr8Xn3brVeNp7r9'},
            'Coimbatore': {'distance': 200, 'link': 'https://maps.app.goo.gl/k6pMfGuFLXP9eLHG7'},
        },
        'Pondicherry': {
            'Bengaluru': {'distance': 0, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
            'Osur': {'distance': 50, 'link': 'https://maps.app.goo.gl/qrhccqZZFPHhYYKE8'},
            'Mathur': {'distance': 80, 'link': 'https://maps.app.goo.gl/m7qXqVA9ZocWpzGo6'},
            'Tiruvannamalai': {'distance': 120, 'link': 'https://maps.app.goo.gl/XH5oUWD9aDhDCwJo9'},
            'Tindivanam': {'distance': 150, 'link': 'https://maps.app.goo.gl/YrEFt5iuCwzubfXr6'},
            'Pondicherry': {'distance': 180, 'link': 'https://maps.app.goo.gl/LhxRtjpLoh1Hu6ZFA'},
        },
        'Trichy': {
            'Bengaluru': {'distance': 0, 'link': 'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
            'Osur': {'distance': 50, 'link': 'https://maps.app.goo.gl/qrhccqZZFPHhYYKE8'},
            'Mathur': {'distance': 80, 'link': 'https://maps.app.goo.gl/m7qXqVA9ZocWpzGo6'},
            'Darmapuri': {'distance': 120, 'link': 'https://maps.app.goo.gl/uUCi83ja7CwBQ44Z7'},
            'Salem': {'distance': 150, 'link': 'https://maps.app.goo.gl/qD99cER1BPM4aLg88'},
            'Paramathi': {'distance': 180, 'link': 'https://maps.app.goo.gl/dAsGtbaMo9RVC4F69'},
            'Trichy': {'distance': 200, 'link': 'https://maps.app.goo.gl/BmRFQUi8gyBzwnGQA'},
        },
        'Arni':{
            'Bengaluru':{'distance':0,'link':'https://maps.app.goo.gl/8SCm2HHyxqxDZSga7'},
            'Hosur':{'distance':35,'link':'https://maps.app.goo.gl/odZMRHaskQk61FPp8'},
            'Krishnagiri':{'distance':90,'link':'https://maps.app.goo.gl/m7qXqVA9ZocWpzGo6'},
            'vaniyambadi':{'distance':140,'link':'https://maps.app.goo.gl/cQh61DEXp2uFBCmW9'},
            'vellore':{'distance':205,'link':'https://maps.app.goo.gl/p9k9ofUwXjUwkj3p9'},
            'Arni':{'distance':235,'link':'https://maps.app.goo.gl/ymW3UK51dr4ih4hr8'},
      },
    },
})